#!/usr/bin/env bash
# comment
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
# This creates a new landing page for your sevrver.
echo "Hello World!" | sudo tee  /var/www/html/index.html
# to apply changes while its still running - reload
sudo sed  -i "/server_name _;/a\
        rewrite ^/redirect_me  https://rumble.com permanent;
" /etc/nginx/sites-enabled/default
sudo service nginx restart
