#!/usr/bin/env bash
# This is to install HAproxy load balancer on ana Nginx web-server
sudo apt update -y
sudo apt-get install --no-install-recommends -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy
sudo systemctl start haproxy
sudo systemctl enable haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
echo "frontend http_front
    bind :80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web1 54.173.64.143:80 check
    server web2 54.210.109.108:80 check

" | sudo tee -a  /etc/haproxy/haproxy.cfg
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
#echo "54.173.64.143   530633-web-01
#54.210.109.108  530633-web-02
#" | sudo tee -a  /etc/hosts 
sudo service haproxy restart 
