#!/usr/bin/env bash
# This is to print Best School 10 times using the while loop.
#M_I_N_E
a=10 #var
while [ $a -ne 0 ]; do #This is the syntax: while [ $var -ne 0 ]; do
        echo "Best School" # echo "string"
	if [ $a == 2 ]
	then	
		echo "Hi"
	fi
	a=$((a - 1)) #increment: var = $((var +/- 1))
done
