#!/usr/bin/env bash
# This script gives information about a `school` file
#R_E_-_D_O
if [ -e "school" ]; then
	echo "school file exists"
else
	echo "school file does not exist"
fi

if [ ! -s "school" ]; then
	echo "school file is empty"
else
	echo "school file is not empty"
fi

if [ -f "school" ]; then
	echo "school is a regular file"
fi
